services:
  backend:
    build: .
    container_name: backend_idmarket
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://database:5432/idmarket
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - APPLICATION_PROFILE=dev
    depends_on:
      - database
    networks:
      - dev

  database:
    image: postgres
    container_name: postgres_database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=idmarket
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    networks:
      - dev

networks:
  dev:
    driver: bridge